apiVersion: v1
kind: Pod
metadata:
  name: {{ .Values.component }}
  labels:
    app.kubernetes.io/name: {{ .Values.component }}
spec:
  containers:
   - name: {{ .Values.component }}
     image: 471200138067.dkr.ecr.us-east-1.amazonaws.com/{{ .Values.component }}:{{.Values.APP_VERSION}}
     initContainers:
   - name:  in-it-cont-parameters
     image: 471200138067.dkr.ecr.us-east-1.amazonaws.com/in-it-cont-parameters:1.0.3