apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{.Values.component}}
  Annotations:
    eks.amazonaws.com/role-arn: eks.amazonaws.com/role-arn:arn:aws:iam::471200138067:role/ssm-get-parameter
  labels:
    app.kubernetes.io/name: {{.Values.component}}